version: '3'
services:
  app:
    build:
      context: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14.9-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env
